on: [push]

jobs:
  hello_action:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: My first step - check out repository
        uses: actions/checkout@v4

      - name: Hello world action step
        uses: ./
